### ISSUE TITLE
请求添加高中3000词词库

### ISSUE THREAD

**Issue by yeshuchen** [RealKai42/qwerty-learner#632]
对于我这样的高中生来说，这个项目也十分有用，因此我建议添加高中3000词

**Comment by Silence-dream** [comment]
可以参考 https://github.com/Kaiyiwing/qwerty-learner/blob/dev/public/dicts/NCE_1.json#L1  贡献你所需要的词典

**Comment by yeshuchen** [comment]
@Silence-dream  thanks
