### ISSUE TITLE
Vercel 域名不带 Referer 访问时会重定向到 /index.html

### ISSUE THREAD

**Issue by CLDXiang** [RealKai42/qwerty-learner#663]
不带 Referer 访问 https://qwerty-learner.vercel.app 和 https://qwerty.kaiyi.cool 这两个域名时，会被重定向到 https://qwerty.kaiyi.cool/index.html ， `#root` 不会渲染任何内容（🤔 Router 的原因？）。

带 Referer 则可以正常重定向到 gitee 站点。

用户直接用域名访问或者从仓库右上方的超链接（`<a rel="noreferer" />`）进入都会不带 Referer，进入不可用状态的 App。

不确定是否是我本地浏览器或网络配置的缘故，如果是个例直接 Close 就好。

![image](https://github.com/RealKai42/qwerty-learner/assets/23160486/7a9a0fea-51f6-4c6f-8acc-87a32fb0542b)

![image](https://github.com/RealKai42/qwerty-learner/assets/23160486/91686f66-dc34-457c-9d8d-eb2924ed71e5)

**Comment by yeshuchen** [comment]
我也遇到这个问题了

**Comment by RealKai42** [comment]
是配置的问题，最近在迁移到阿里云，会有些小问题，已经修复了

**Comment by RealKai42** [comment]
qwerty.kaiyi.cool 重定向到 qwerty.kaiyi.cool/index.html  是符合预期的，为了使用阿里云的 cdn 做部署必须得这样..

**Comment by CLDXiang** [comment]
哈哈，期待踩坑分享，vercel 一挂我两手一摊

**Comment by RealKai42** [comment]
🤣 这两天愁死了
真不熟后端和运维
