### ISSUE TITLE
部署到vercel上如何配置

### ISSUE THREAD

**Issue by i2plus** [RealKai42/qwerty-learner#733]
想要自己部署到vercel上，应该怎么配置啊，能出个一个配置说明么？

**Comment by rubickecho** [comment]
1. fork this project
2. go to `vercel`, add new project and import this project
3. update `Build & Development Settings` -> `Output Directory`: "build"
4. click deploy

**Comment by i2plus** [comment]
> 1. fork this project
> 2. go to `vercel`, add new project and import this project
> 3. update `Build & Development Settings` -> `Output Directory`: "build"
> 4. click deploy

thanks
