### ISSUE TITLE
【bug】firefox浏览器日语拼写输入  '  分号，会触发浏览器快速查找（仅链接）栏

### ISSUE THREAD

**Issue by Oshibuki** [RealKai42/qwerty-learner#754]
update: 
firefox有个按键'（单引号）打开快速查找（仅链接）栏的快捷键，似乎需要阻止该事件冒泡到浏览器层面
---
firefox浏览器，在拼写“雰囲気”(fun'iki)的时候，当输入到  ‘  这个分号，程序会误以为输入无效，提示：“按任意键继续”，主要区域出现模糊滤镜。
具体如下图
[gif截图](https://imgur.com/a/CRWsZPc)

**Comment by Muzych** [comment]
图挂了哥们
