### ISSUE TITLE
**功能请求** 支持拼写一段文本, 更符合实际的应用场景

### ISSUE THREAD

**Issue by NilCent** [RealKai42/qwerty-learner#763]
我希望可以在一张卡片中拼写一个句子, 或是一段文字. 
` What is the idiomatic Go equivalent of C's ternary operator? `
or
```
#!/bin/bash
for(i := 0; i < 3; i++) {
    fmt.Printf("%d\n", i)
}
```
这样可以同时练习到拼写字母和常用符号. 更符合实际的应用场景.

在此之上, 我希望可以做到以下三点:
+ 英文语句可以保持**朗读**的功能. 目前是json中配置`音标, 不知道可不可以调 Google 翻译.
+ 目前单词输错了, 会回滚到单词开头. 希望可以添加一个仅提示错误**不回滚**, 由用户自己删除错误字符的选项.
+ 可以更方便地在**本地**创建, 导入, 导出卡片集. 可以让用户来积累自己的卡片集.

**Comment by cc20140820** [comment]
+1
