### ISSUE TITLE
[BUG] 译林版词典 接口请求404

### ISSUE THREAD

**Issue by ZQH237474513** [RealKai42/qwerty-learner#774]
![image](https://github.com/RealKai42/qwerty-learner/assets/95038955/7b0784cc-4d21-480c-bf41-826556adcf14)

**Comment by luojiyin1987** [comment]
![image](https://github.com/RealKai42/qwerty-learner/assets/6524977/ee2f4b38-020b-426e-8d25-d7bb8724e64c)
我是可以正常访问到的

**Comment by ZQH237474513** [comment]
![image](https://github.com/RealKai42/qwerty-learner/assets/95038955/aa794880-87d8-427e-b65a-06e3503b43e1)

/dicts 前面多了一个点导致

![image](https://github.com/RealKai42/qwerty-learner/assets/95038955/549b7513-fb21-471d-bf22-6087dbb056d3)

**Comment by luojiyin1987** [comment]
问题解决了，麻烦关闭 issue  @ZQH237474513
