### ISSUE TITLE
feat: 将页脚备案号移出主分支

### ISSUE THREAD

**Issue by ShiinaKin** [RealKai42/qwerty-learner#796]
![image](https://github.com/RealKai42/qwerty-learner/assets/52254895/b96940eb-13f5-48a1-85ff-7ae7bee03c1a)

如图，这是我通过vercel部署的，仍然有备案号

**Comment by RealKai42** [comment]
目前主分支关联在线上部署中，移除后可能违反部分地区的相关规定
